import {mkdir} from "node:fs/promises";
import path from "node:path";
import {expect,test} from "@playwright/test";

const matrix=[["1920",1920,1080],["1600",1600,900],["1440",1440,900],["1366",1366,768],["1280",1280,720],["1024",1024,768],["820",820,1180],["768",768,1024],["430",430,932],["414",414,896],["393",393,852],["390",390,844],["375",375,812],["360",360,800]] as const;
const captureStage=process.env.FINAL_CAPTURE;
async function ready(page:import("@playwright/test").Page,locale:string){await page.goto(`/${locale}`,{waitUntil:"load"});await page.locator("main").waitFor({state:"visible"});await page.waitForTimeout(350)}
async function loadLazyMedia(page:import("@playwright/test").Page){for(const id of ["expeditions","story","format","archive","about","contact"]){await page.locator(`#${id}`).scrollIntoViewIfNeeded();await page.waitForTimeout(180)}await page.evaluate(()=>{document.documentElement.style.scrollBehavior="auto";scrollTo(0,0)});await page.waitForTimeout(250)}

test.describe("final layout diagnostics",()=>{
 for(const locale of ["ru","en"]){for(const [label,width,height] of matrix){test(`${locale} ${label} layout bounds`,async({page})=>{await page.setViewportSize({width,height});await ready(page,locale);const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,ui:Array.from(document.querySelectorAll<HTMLElement>("header .logo, header .languageSwitch, .menuButton, .heroBottom a, #contact form, footer")).filter(el=>getComputedStyle(el).display!=="none").map(el=>{const b=el.getBoundingClientRect();return{name:el.className||el.tagName,left:b.left,right:b.right,width:b.width,height:b.height}})}));expect(result.overflow).toBe(0);for(const item of result.ui){expect(item.width).toBeGreaterThan(0);expect(item.height).toBeGreaterThan(0);expect(item.left).toBeGreaterThanOrEqual(-1);expect(item.right).toBeLessThanOrEqual(width+1)}})}}
 test("mobile menu and destination select remain reachable",async({page})=>{await page.setViewportSize({width:360,height:800});await ready(page,"ru");await page.locator(".menuButton").click();await expect(page.locator(".mobileMenu")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBe(0);await page.locator(".menuButton").click();await page.locator("#contact").scrollIntoViewIfNeeded();await page.locator(".destinationTrigger").click();await expect(page.locator(".destinationMenu")).toBeVisible();const menu=await page.locator(".destinationMenu").boundingBox();expect(menu).not.toBeNull();expect(menu!.x).toBeGreaterThanOrEqual(0);expect(menu!.x+menu!.width).toBeLessThanOrEqual(360);expect(menu!.y).toBeGreaterThanOrEqual(0);expect(menu!.y+menu!.height).toBeLessThanOrEqual(800);await page.locator(".destinationMenu button").nth(2).click();await expect(page.locator(".destinationTrigger")).toContainText("Байкал")});
 test("runtime stays clean through full scroll",async({page})=>{const errors:string[]=[];page.on("console",message=>{if(message.type()==="error"||message.type()==="warning")errors.push(message.text())});page.on("pageerror",error=>errors.push(error.message));await ready(page,"en");for(const id of ["top","expeditions","story","format","archive","about","contact"]){await page.locator(`#${id}`).scrollIntoViewIfNeeded();await page.waitForTimeout(180)}expect(errors).toEqual([])});
});

test.describe("final visual captures",()=>{test.skip(!captureStage,"Set FINAL_CAPTURE to create QA screenshots");for(const locale of ["ru","en"]){for(const [label,width,height] of matrix){test(`${captureStage} ${locale} ${label}`,async({page})=>{await page.emulateMedia({reducedMotion:"reduce"});await page.setViewportSize({width,height});await ready(page,locale);await loadLazyMedia(page);const directory=path.join(process.cwd(),"qa","final",captureStage!);await mkdir(directory,{recursive:true});await page.screenshot({path:path.join(directory,`${locale}-${label}.png`),fullPage:true,animations:"disabled"})})}}});

test("approved key scenes",async({page})=>{
 test.skip(captureStage!=="approved");
 const directory=path.join(process.cwd(),"qa","final","approved");await mkdir(directory,{recursive:true});await page.setViewportSize({width:1440,height:900});await ready(page,"ru");
 await page.locator("#top").screenshot({path:path.join(directory,"hero.png"),animations:"disabled"});
 await page.locator("#expeditions").scrollIntoViewIfNeeded();await page.waitForTimeout(500);await page.locator(".expeditionCard").nth(3).hover();await page.locator("#expeditions").screenshot({path:path.join(directory,"expeditions.png"),animations:"allow"});
 await page.evaluate(()=>{document.documentElement.style.scrollBehavior="auto";const section=document.querySelector<HTMLElement>("#story")!;scrollTo(0,section.getBoundingClientRect().top+scrollY+(section.offsetHeight-innerHeight)*.5)});await page.waitForTimeout(500);await page.screenshot({path:path.join(directory,"story-50.png"),animations:"allow"});
 for(const [name,selector] of [["format","#format"],["field-log","#archive"],["final-cta","#contact"]] as const){await page.locator(selector).scrollIntoViewIfNeeded();await page.waitForTimeout(900);await page.locator(selector).screenshot({path:path.join(directory,`${name}.png`),animations:"disabled"})}
 await page.locator(".destinationTrigger").click();await page.waitForTimeout(200);await page.locator("#contact").screenshot({path:path.join(directory,"destination-open.png"),animations:"disabled"});
});
