"use client";
/* eslint-disable @next/next/no-location-assign-relative-destination */
import Image from "next/image";
import {useEffect,useRef,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import {content,type Locale} from "@/content";

const Arrow=()=> <span aria-hidden>↘</span>;
const scenes=[["road","hero-01.jpeg",".principles","center 62%"],["mountains","kyrgyzstan-03.jpeg","#expeditions","center 48%"],["pacific","kurils-03.jpeg",".story","center 52%"],["memory","dagestan-03.jpeg","#archive","center 55%"],["people","home-03.jpeg","#about","center 48%"]] as const;
const formatImages=["home-02.jpeg","kamchatka-02.jpeg","home-04.jpeg","kurils-01.jpeg","kurils-02.jpeg"];

function PageEnvironment(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current||matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{const layers=gsap.utils.toArray<HTMLElement>(".environmentScene");let stops:number[]=[];const measure=()=>{stops=scenes.map((s,i)=>i===0?0:(document.querySelector(s[2])?.getBoundingClientRect().top??0)+scrollY)};const render=(y:number)=>{const focus=y+innerHeight*.56;let current=0;while(current<stops.length-1&&focus>=stops[current+1])current++;const next=Math.min(current+1,layers.length-1),start=stops[current]??0,end=stops[next]??start+innerHeight,blend=next===current?0:gsap.utils.clamp(0,1,(focus-start)/Math.max(end-start,1));layers.forEach((layer,index)=>{const opacity=index===current?1-blend:index===next?blend:0,local=index===current?blend:index===next?blend-1:0;gsap.set(layer,{opacity,scale:innerWidth<=900?1:1.065-Math.abs(local)*.025,yPercent:innerWidth<=900?0:local*-2.5})})};measure();const controller=ScrollTrigger.create({trigger:document.documentElement,start:"top top",end:"bottom bottom",onRefresh:measure,onUpdate:self=>render(self.scroll())});render(scrollY);return()=>controller.kill()},ref);return()=>ctx.revert()},[]);return <div className="pageEnvironment" ref={ref} aria-hidden>{scenes.map((s,i)=><div className={`environmentScene${i===0?" active":""}`} key={s[0]}><Image src={`/images/madrussians/${s[1]}`} alt="" fill sizes="100vw" quality={82} style={{objectPosition:s[3]}}/></div>)}<div className="environmentVeil"/></div>}

function LanguageSwitch({locale,onSwitch}:{locale:Locale;onSwitch:(next:Locale)=>void}){return <div className="languageSwitch" aria-label="Language"><button className={locale==="ru"?"active":""} onClick={()=>onSwitch("ru")}>RU</button><span>/</span><button className={locale==="en"?"active":""} onClick={()=>onSwitch("en")}>EN</button></div>}

/* eslint-disable react-hooks/set-state-in-effect */

function DestinationSelect({options,placeholder,aria}:{options:string[];placeholder:string;aria:string}){const [value,setValue]=useState(""),[open,setOpen]=useState(false),[active,setActive]=useState(0);const ref=useRef<HTMLDivElement>(null),listId="destination-options";useEffect(()=>{setValue("");setOpen(false)},[options]);useEffect(()=>{const close=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);const choose=(i:number)=>{setValue(options[i]);setActive(i);setOpen(false)};const show=()=>{ref.current?.scrollIntoView({block:"center"});setOpen(true)};const keys=(e:React.KeyboardEvent<HTMLButtonElement>)=>{if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();show();setActive(i=>open?(i+(e.key==="ArrowDown"?1:-1)+options.length)%options.length:Math.max(options.indexOf(value),0))}else if((e.key==="Enter"||e.key===" ")&&open){e.preventDefault();choose(active)}else if(e.key==="Escape")setOpen(false)};return <div className={`destinationSelect${open?" open":""}`} ref={ref}><input type="hidden" name="destination" value={value}/><button type="button" className="destinationTrigger" role="combobox" aria-labelledby="destination-label" aria-expanded={open} aria-controls={listId} aria-haspopup="listbox" onClick={()=>open?setOpen(false):show()} onKeyDown={keys}><span className={value?"selected":""}>{value||placeholder}</span><span className="destinationChevron">↓</span></button><div className="destinationMenu" id={listId} role="listbox" aria-label={aria}>{options.map((option,i)=><button type="button" role="option" aria-selected={value===option} className={`${active===i?"active ":""}${value===option?"selected":""}`} onPointerMove={()=>setActive(i)} onClick={()=>choose(i)} key={option}><span>{option}</span><i>{value===option?"•":"→"}</i></button>)}</div></div>}

export default function Site({locale}:{locale:Locale}){const t=content[locale];const [menu,setMenu]=useState(false),[activeFormat,setActiveFormat]=useState(0);const root=useRef<HTMLDivElement>(null);
useEffect(()=>{document.documentElement.lang=locale;history.scrollRestoration="manual"},[locale]);useEffect(()=>{document.body.style.overflow=menu?"hidden":"";return()=>{document.body.style.overflow=""}},[menu]);
useEffect(()=>{const audit=new URLSearchParams(location.search).get("audit");if(!audit)return;document.body.dataset.audit=audit;return()=>{delete document.body.dataset.audit}},[]);
useEffect(()=>{if(!root.current||matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{if(!navigator.webdriver){gsap.fromTo(".heroImage",{scale:1.045},{scale:1,duration:1.8,ease:"power3.out"});gsap.from(".heroReveal",{yPercent:115,duration:1.05,stagger:.12,ease:"power3.out",delay:.15})}else gsap.set(".heroImage",{scale:1});gsap.to(".heroImage",{yPercent:8,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});gsap.from(".expeditionCard",{clipPath:"inset(100% 0 0 0)",duration:1.1,stagger:.1,ease:"power3.out",scrollTrigger:{trigger:".expeditionGrid",start:"top 82%"}});if(matchMedia("(min-width: 901px)").matches){const story=gsap.timeline({scrollTrigger:{trigger:".story",start:"top top",end:"bottom bottom",scrub:1}});story.from(".storyLine",{yPercent:120,stagger:.12},0).from(".storyMedia",{scale:.88,opacity:0,stagger:.08},.08).to(".depthBack",{yPercent:-10},0).to(".depthMid",{yPercent:-20},0).to(".depthFront",{yPercent:-32},0)}},root);const refresh=()=>ScrollTrigger.refresh();window.addEventListener("load",refresh);return()=>{window.removeEventListener("load",refresh);ctx.revert()}},[locale]);
const switchLocale=(next:Locale)=>{if(next===locale)return;const sections=Array.from(document.querySelectorAll<HTMLElement>("main section[id]"));const anchor=sections.filter(s=>s.getBoundingClientRect().top<=innerHeight*.45).at(-1)??sections[0];const id=anchor?.id??"top",offset=anchor?scrollY-(anchor.getBoundingClientRect().top+scrollY):scrollY,state={id,offset,hash:location.hash};sessionStorage.setItem("ravenorth-locale-scroll",JSON.stringify(state));location.assign(`/${next}?section=${encodeURIComponent(id)}&offset=${Math.round(offset)}&returnHash=${encodeURIComponent(location.hash)}#${id}`)};useEffect(()=>{const params=new URLSearchParams(location.search),stored=sessionStorage.getItem("ravenorth-locale-scroll");const raw=stored??(params.has("section")?JSON.stringify({id:params.get("section"),offset:Number(params.get("offset")??0),hash:params.get("returnHash")??""}):null);if(!raw)return;const timer=setTimeout(()=>requestAnimationFrame(()=>{const {id,offset,hash}=JSON.parse(raw) as {id:string;offset:number;hash:string};const target=document.getElementById(id),html=document.documentElement,previous=html.style.scrollBehavior;html.style.scrollBehavior="auto";history.replaceState(null,"",`/${locale}${hash}`);ScrollTrigger.refresh();const top=target?target.getBoundingClientRect().top+scrollY+offset:0;html.scrollTop=top;document.body.scrollTop=top;requestAnimationFrame(()=>{html.scrollTop=top;document.body.scrollTop=top;ScrollTrigger.refresh();sessionStorage.removeItem("ravenorth-locale-scroll");requestAnimationFrame(()=>{html.style.scrollBehavior=previous})})}),120);return()=>clearTimeout(timer)},[locale]);
return <div ref={root} className="siteShell"><PageEnvironment/>
<header className="header"><a className="logo" href="#top">RAVENORTH</a><span className="conceptBadge">EO LABS CONCEPT / 2026</span><nav aria-label={t.menu.aria}>{t.navigation.map(x=><a href={x.href} key={x.href}>{x.label}</a>)}<a className="headerCta" href="#contact">{locale==="ru"?"СМОТРЕТЬ КОНЦЕПТ":"EXPLORE"} →</a></nav><LanguageSwitch locale={locale} onSwitch={switchLocale}/><button className="menuButton" onClick={()=>setMenu(!menu)} aria-expanded={menu}>{menu?t.menu.close:t.menu.open}</button></header>
{menu&&<div className="mobileMenu">{t.navigation.map(x=><a key={x.href} href={x.href} onClick={()=>setMenu(false)}>{x.label}<Arrow/></a>)}<LanguageSwitch locale={locale} onSwitch={switchLocale}/><span className="mobileConcept">EO LABS CONCEPT / 2026</span></div>}
<main><section className="hero" id="top"><Image src="/images/madrussians/hero-01.jpeg" alt="Remote mountain road" fill priority sizes="100vw" className="cover heroImage"/><div className="shade"/><p className="eyebrow heroEyebrow heroReveal">{t.hero.eyebrow}</p><h1>{t.hero.lines.map(line=><span className="heroClip" key={line}><b className="heroReveal">{line}</b></span>)}</h1><div className="heroBottom"><p>KAMCHATKA · KURILS · BAIKAL · CAUCASUS · TIAN SHAN</p><p>{t.hero.description}</p><a href="#expeditions">{t.hero.cta} <Arrow/></a></div><aside className="sideNav" aria-label={t.hero.sectionsAria}>{t.navigation.map((x,i)=><a href={x.href} key={x.href}>0{i+1} / {x.label}</a>)}<a href="#contact">05 / {locale==="ru"?"ДАЛЬШЕ":"NEXT"}</a></aside><span className="scroll">{t.hero.scroll} ↓</span></section>
<section className="principles section">{t.principles.map(([n,title,description])=><article key={n}><span>{n}</span><h2>{title}</h2><p>{description}</p></article>)}</section>
<section className="expeditions section" id="expeditions"><div className="sectionHead"><p className="eyebrow">{t.expeditionSection.eyebrow}</p><h2>{t.expeditionSection.title[0]}<br/><i>{t.expeditionSection.title[1]}</i></h2><p>{t.expeditionSection.description}</p></div><div className="expeditionGrid">{t.expeditions.map((e,i)=><a className="expeditionCard" href="#contact" key={e.slug}><Image src={e.image} alt={e.destination} fill sizes="(max-width: 700px) 88vw, 28vw"/><span className="cardShade"/><span className="cardIndex">{String(i+1).padStart(2,"0")}</span><div className="cardBody"><span>{e.destination}</span><h3>{e.title}</h3><p>{e.season}</p><div><b>{e.duration} · {e.group}</b><em>{t.expeditionSection.open} <Arrow/></em></div></div></a>)}</div></section>
<section className="story" id="story"><div className="storyStage">{["kamchatka-03.jpeg","kurils-01.jpeg","kamchatka-02.jpeg","baikal-02.jpeg","home-02.jpeg"].map((name,i)=><div className={`storyMedia s${i+1} ${["depthBack","depthMid","depthFront","depthBack","depthMid"][i]}`} key={name}><Image src={`/images/madrussians/${name}`} alt="" fill sizes="30vw"/></div>)}<p className="eyebrow">{t.story.eyebrow}</p><h2>{t.story.lines.map((line,i)=><span className="storyClip" key={line}><b className="storyLine">{i===2?<i>{line}</i>:line}</b></span>)}</h2><div className="storyNote">{t.story.note}<br/><span>DESTINATION STUDY</span></div></div></section>
<section className="format section" id="format"><div className="formatTitle"><p className="eyebrow">{t.format.eyebrow}</p><h2>{t.format.title[0]}<br/><i>{t.format.title[1]}</i></h2><div className="formatList">{t.format.items.map(([n,title,description],i)=><button key={n} onMouseEnter={()=>setActiveFormat(i)} onFocus={()=>setActiveFormat(i)} onClick={()=>setActiveFormat(i)} className={activeFormat===i?"active":""}><span>{n}</span><strong>{title}</strong><em>{description}</em><Arrow/></button>)}</div></div><div className="formatStage">{formatImages.map((name,i)=><Image key={name} src={`/images/madrussians/${name}`} alt={t.format.imageAlt} fill sizes="48vw" className={activeFormat===i?"active":""}/>)}<span>0{activeFormat+1} / {t.format.stageLabel}</span></div></section>
<section className="archive section" id="archive"><div className="sectionHead archiveHead"><p className="eyebrow">{t.fieldLog.eyebrow}</p><h2>{t.fieldLog.title[0]}<br/><i>{t.fieldLog.title[1]}</i></h2></div><div className="archiveTrack">{t.fieldLog.items.map((item,i)=><figure key={item.place}><div><Image src={item.image} alt={item.place} fill sizes="(max-width:700px) 80vw, 38vw"/></div><figcaption><span>0{i+1}</span><b>{item.place}</b><em>{item.study}</em></figcaption></figure>)}</div></section>
<section className="about section" id="about"><div><p className="eyebrow">{t.about.eyebrow}</p><div className="aboutStat"><strong>{String(t.expeditions.length).padStart(2,"0")}</strong><span>{t.about.metricLabel.split("\n").map(x=><span key={x}>{x}<br/></span>)}</span></div><h2>{t.about.title[0]}<br/><i>{t.about.title[1]}</i></h2></div><div className="aboutCopy"><p>{t.about.paragraphs[0]}</p><p>{t.about.paragraphs[1]}</p><div className="aboutImage"><Image src="/images/madrussians/kurils-02.jpeg" alt={t.about.imageAlt} fill sizes="45vw"/></div></div></section>
<section className="reviews editorial section"><p className="eyebrow">{t.editorial.eyebrow}</p><h2>{t.editorial.title[0]}<br/><i>{t.editorial.title[1]}</i></h2><div className="editorialGrid">{t.editorial.items.map(([n,title,description])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
<section className="contact section" id="contact"><Image src="/images/madrussians/home-02.jpeg" alt={t.contact.imageAlt} fill sizes="100vw" className="contactBg"/><div className="contactShade"/><p className="eyebrow">{t.contact.eyebrow}</p><h2>{t.contact.title[0]}<br/><i>{t.contact.title[1]}</i></h2><div className="contactGrid"><p>{t.contact.supporting}</p><form onSubmit={e=>e.preventDefault()}>{(["name","contact"] as const).map(key=><label key={key}>{t.contact.fields[key][0]}<input name={key} placeholder={t.contact.fields[key][1]}/></label>)}<div className="contactField"><span id="destination-label">{t.contact.fields.destination[0]}</span><DestinationSelect options={t.contact.destinations} placeholder={t.contact.fields.destination[1]} aria={t.contact.destinationsAria}/></div><label>{t.contact.fields.dates[0]}<input name="dates" placeholder={t.contact.fields.dates[1]}/></label><button type="submit" aria-disabled>{t.contact.submit}</button><small>{t.contact.note}</small></form></div></section></main>
<footer><div><div className="logo">RAVENORTH</div><span className="footerConcept">EO LABS CONCEPT / 2026</span></div><p>{t.footer.descriptor}</p><p className="footerDisclaimer">{t.footer.disclaimer}</p><a href="https://eolabs.ru/" target="_blank" rel="noopener noreferrer">{t.footer.direction} ↗</a></footer></div>}
