"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import {expeditions} from "@/data/expeditions";
import {archive} from "@/data/archive";
import {reviews} from "@/data/reviews";
import {formatItems,principles,site} from "@/data/site";

const Arrow=()=> <span aria-hidden>↘</span>;
export default function Site(){
 const [menu,setMenu]=useState(false); const [review,setReview]=useState(0); const [activeFormat,setActiveFormat]=useState(0);
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{document.body.style.overflow=menu?"hidden":"";return()=>{document.body.style.overflow=""}},[menu]);
 useEffect(()=>{if(!root.current||matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{
   if(!navigator.webdriver){
     gsap.fromTo(".heroImage",{scale:1.045},{scale:1,duration:1.8,ease:"power3.out"});
     gsap.from(".heroReveal",{yPercent:115,duration:1.05,stagger:.12,ease:"power3.out",delay:.15});
   } else {
     gsap.set(".heroImage",{scale:1});
   }
   gsap.to(".heroImage",{yPercent:8,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});
   gsap.from(".expeditionCard",{clipPath:"inset(100% 0 0 0)",duration:1.1,stagger:.1,ease:"power3.out",scrollTrigger:{trigger:".expeditionGrid",start:"top 82%"}});
   const story=gsap.timeline({scrollTrigger:{trigger:".story",start:"top top",end:"bottom bottom",scrub:1}});
   story.from(".storyLine",{yPercent:120,stagger:.12,ease:"power3.out"},0).from(".storyMedia",{scale:.88,opacity:0,stagger:.08,ease:"power2.out"},.08).to(".depthBack",{yPercent:-10,ease:"none"},0).to(".depthMid",{yPercent:-20,ease:"none"},0).to(".depthFront",{yPercent:-32,ease:"none"},0);
 },root);const refresh=()=>ScrollTrigger.refresh();window.addEventListener("load",refresh);return()=>{window.removeEventListener("load",refresh);ctx.revert()}},[]);
 const formatImages=["/images/madrussians/home-02.jpeg","/images/madrussians/kamchatka-02.jpeg","/images/madrussians/home-04.jpeg","/images/madrussians/kurils-01.jpeg","/images/madrussians/kurils-02.jpeg"];
 return <div ref={root}>
  <header className="header"><a className="logo" href="#top">MADRUSSIANS</a><nav aria-label="Основная навигация"><a href="#expeditions">ЭКСПЕДИЦИИ</a><a href="#about">О ПРОЕКТЕ</a><a href="#archive">АРХИВ</a><a href="#contact">КОНТАКТЫ</a><a className="headerCta" href="#contact">ПОЕХАЛИ →</a></nav><button className="menuButton" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Открыть меню">{menu?"ЗАКРЫТЬ":"МЕНЮ"}</button></header>
  {menu&&<div className="mobileMenu">{[["ЭКСПЕДИЦИИ","#expeditions"],["О ПРОЕКТЕ","#about"],["АРХИВ","#archive"],["КОНТАКТЫ","#contact"]].map(x=><a key={x[0]} href={x[1]} onClick={()=>setMenu(false)}>{x[0]} <Arrow/></a>)}</div>}
  <main>
   <section className="hero" id="top"><Image src="/images/madrussians/hero-01.jpeg" alt="Автомобиль экспедиции MADRUSSIANS на дороге среди гор" fill priority sizes="100vw" className="cover heroImage"/><div className="shade"/><p className="eyebrow heroEyebrow heroReveal">{site.tagline}</p><h1><span className="heroClip"><b className="heroReveal">НЕ ТУРЫ.</b></span><span className="heroClip"><b className="heroReveal">ЭКСПЕДИЦИИ.</b></span></h1><div className="heroBottom"><p>KAMCHATKA · KURILS · BAIKAL · CAUCASUS · TIAN SHAN</p><p>Маленькие группы. Большие расстояния. Места, куда редко добираются обычные путешественники.</p><a href="#expeditions">СМОТРЕТЬ ЭКСПЕДИЦИИ <Arrow/></a></div><aside className="sideNav" aria-label="Разделы"><a href="#expeditions">01 / ЭКСПЕДИЦИИ</a><a href="#format">02 / ФОРМАТ</a><a href="#archive">03 / АРХИВ</a><a href="#about">04 / О НАС</a><a href="#contact">05 / ПОЕХАЛИ</a></aside><span className="scroll">SCROLL ↓</span></section>
   <section className="principles section">{principles.map(([n,t,d])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></article>)}</section>
   <section className="expeditions section" id="expeditions"><div className="sectionHead"><p className="eyebrow">01 / SELECTED ROUTES</p><h2>EXPEDITIONS<br/><i>2026—27</i></h2><p>Маршруты, после которых обычный отпуск воспринимается немного иначе.</p></div><div className="expeditionGrid">{expeditions.map((e,i)=><Link className="expeditionCard" href={e.href} key={e.slug}><Image src={e.image} alt={e.title} fill sizes="(max-width: 700px) 88vw, 28vw"/><span className="cardShade"/><span className="cardIndex">0{i+1}</span><div className="cardBody"><span>{e.destination}</span><h3>{e.title}</h3><p>{e.dates.join(" / ")}</p><div><b>{e.price}</b><em>ОТКРЫТЬ <Arrow/></em></div></div></Link>)}</div></section>
   <section className="story"><div className="storyStage"><div className="storyMedia s1 depthBack"><Image src="/images/madrussians/kamchatka-03.jpeg" alt="Камчатка" fill sizes="38vw"/></div><div className="storyMedia s2 depthMid"><Image src="/images/madrussians/kurils-01.jpeg" alt="Северные Курилы" fill sizes="25vw"/></div><div className="storyMedia s3 depthFront"><Image src="/images/madrussians/kamchatka-02.jpeg" alt="Внедорожники на Камчатке" fill sizes="28vw"/></div><div className="storyMedia s4 depthBack"><Image src="/images/madrussians/baikal-02.jpeg" alt="Лёд Байкала" fill sizes="30vw"/></div><div className="storyMedia s5 depthMid"><Image src="/images/madrussians/home-02.jpeg" alt="Участник экспедиции у океана" fill sizes="24vw"/></div><div className="storyMedia s6 depthFront"><Image src="/images/madrussians/kyrgyzstan-02.jpg" alt="Ночь в Тянь-Шане" fill sizes="32vw"/></div><p className="eyebrow">FIELD NOTES / RUSSIA & BEYOND</p><h2><span className="storyClip"><b className="storyLine">ТУДА,</b></span><span className="storyClip"><b className="storyLine">ГДЕ КОНЧАЮТСЯ</b></span><span className="storyClip"><b className="storyLine"><i>ДОРОГИ.</i></b></span></h2><div className="storyNote">KAMCHATKA / 2025<br/><span>OFF ROAD / FIELD NOTE</span></div></div></section>
   <section className="format section" id="format"><div className="formatTitle"><p className="eyebrow">02 / THE FORMAT</p><h2>НЕ КАК<br/><i>ОБЫЧНЫЙ ТУР.</i></h2><div className="formatList">{formatItems.map(([n,t,d],i)=><button key={n} onMouseEnter={()=>setActiveFormat(i)} onFocus={()=>setActiveFormat(i)} onClick={()=>setActiveFormat(i)} className={activeFormat===i?"active":""}><span>{n}</span><strong>{t}</strong><em>{d}</em><Arrow/></button>)}</div></div><div className="formatStage">{formatImages.map((src,i)=><Image key={src} src={src} alt="Формат экспедиции MADRUSSIANS" fill sizes="48vw" className={activeFormat===i?"active":""}/>) }<span>0{activeFormat+1} / MADRUSSIANS FORMAT</span></div></section>
   <section className="archive section" id="archive"><div className="sectionHead archiveHead"><p className="eyebrow">03 / TRAVEL LOG</p><h2>{site.tripCount} ЭКСПЕДИЦИЯ.<br/><i>И ЭТО ТОЛЬКО НАЧАЛО.</i></h2></div><div className="archiveTrack">{archive.map((a,i)=><figure key={a.place}><div><Image src={a.image} alt={a.place} fill sizes="(max-width:700px) 80vw, 38vw"/></div><figcaption><span>0{i+1}</span><b>{a.place}</b><em>{a.date}</em></figcaption></figure>)}</div></section>
   <section className="about section" id="about"><div><p className="eyebrow">04 / ABOUT MADRUSSIANS</p><div className="aboutStat"><strong>61</strong><span>ЭКСПЕДИЦИЯ<br/>С 2021</span></div><h2>PEOPLE<br/>WHO GO<br/><i>FURTHER.</i></h2></div><div className="aboutCopy"><p>Маленькие группы, специальные способы доставки и комфорт даже там, где заканчиваются обычные маршруты.</p><p>Внедорожники, яхты и профессиональный фотограф помогают добраться дальше — и сохранить путешествие не только в памяти.</p><div className="aboutImage"><Image src="/images/madrussians/kurils-02.jpeg" alt="Участница экспедиции MADRUSSIANS на Камчатке" fill sizes="45vw"/></div></div></section>
   <section className="reviews section"><p className="eyebrow">05 / FROM THE ROAD</p><div className="quoteMark">“</div><blockquote>{reviews[review].text}</blockquote><div className="reviewMeta"><p><b>{reviews[review].name}</b><span>{reviews[review].route}</span></p><div>{reviews.map((_,i)=><button aria-label={`Отзыв ${i+1}`} className={review===i?"active":""} onClick={()=>setReview(i)} key={i}>{String(i+1).padStart(2,"0")}</button>)}</div></div></section>
   <section className="contact section" id="contact"><Image src="/images/madrussians/home-02.jpeg" alt="Побережье экспедиции MADRUSSIANS" fill sizes="100vw" className="contactBg"/><div className="contactShade"/><p className="eyebrow">NEXT DEPARTURE / YOUR CALL</p><h2>КУДА<br/>ПОЕДЕМ<br/><i>ДАЛЬШЕ?</i></h2><div className="contactGrid"><p>Расскажите, куда хотите попасть. Команда поможет подобрать экспедицию.</p><form onSubmit={e=>e.preventDefault()}><label>ИМЯ<input name="name" required placeholder="Как вас зовут"/></label><label>КАК СВЯЗАТЬСЯ<input name="contact" required placeholder="Telegram или телефон"/></label><label>КУДА ХОТИТЕ ПОЕХАТЬ<input name="destination" placeholder="Направление"/></label><label>УДОБНЫЕ ДАТЫ<input name="dates" placeholder="Когда вам удобно"/></label><button type="submit">ОСТАВИТЬ ЗАЯВКУ →</button><small>Демо-форма: отправка будет подключена после согласования.</small></form></div></section>
  </main>
  <footer><div className="logo">MADRUSSIANS</div><p>{site.tagline}</p><div><a href={site.telegram}>TELEGRAM</a><a href={site.whatsapp}>WHATSAPP</a><a href={site.instagram}>INSTAGRAM</a></div><p>© 2026 · CONCEPT REDESIGN</p></footer>
 </div>;
}
